package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 9:11:42 PM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * IndexSecteurCandidature generated by hbm2java
 */
@Entity
@Table(name="index_secteur_candidature"
    ,schema="public"
)
public class IndexSecteurCandidature  implements java.io.Serializable {


     private int id;
     private Candidature candidature;
     private SecteurActivite secteurActivite;

    public IndexSecteurCandidature() {
    }

    public IndexSecteurCandidature(int id, Candidature candidature, SecteurActivite secteurActivite) {
       this.id = id;
       this.candidature = candidature;
       this.secteurActivite = secteurActivite;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_candidature", nullable=false)
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_secteur_activite", nullable=false)
    public SecteurActivite getSecteurActivite() {
        return this.secteurActivite;
    }
    
    public void setSecteurActivite(SecteurActivite secteurActivite) {
        this.secteurActivite = secteurActivite;
    }




}


