package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 9:11:42 PM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * IndexSecteurOffre generated by hbm2java
 */
@Entity
@Table(name="index_secteur_offre"
    ,schema="public"
)
public class IndexSecteurOffre  implements java.io.Serializable {


     private int id;
     private OffresEmploi offresEmploi;
     private SecteurActivite secteurActivite;

    public IndexSecteurOffre() {
    }

    public IndexSecteurOffre(int id, OffresEmploi offresEmploi, SecteurActivite secteurActivite) {
       this.id = id;
       this.offresEmploi = offresEmploi;
       this.secteurActivite = secteurActivite;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_offre", nullable=false)
    public OffresEmploi getOffresEmploi() {
        return this.offresEmploi;
    }
    
    public void setOffresEmploi(OffresEmploi offresEmploi) {
        this.offresEmploi = offresEmploi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_secteur_activite", nullable=false)
    public SecteurActivite getSecteurActivite() {
        return this.secteurActivite;
    }
    
    public void setSecteurActivite(SecteurActivite secteurActivite) {
        this.secteurActivite = secteurActivite;
    }




}


