package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 9:11:42 PM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * NiveauxQualification generated by hbm2java
 */
@Entity
@Table(name="niveaux_qualification"
    ,schema="public"
)
public class NiveauxQualification  implements java.io.Serializable {


     private int id;
     private String intitule;
     private Set<OffresEmploi> offresEmplois = new HashSet<OffresEmploi>(0);
     private Set<Candidature> candidatures = new HashSet<Candidature>(0);

    public NiveauxQualification() {
    }

	
    public NiveauxQualification(int id) {
        this.id = id;
    }
    public NiveauxQualification(int id, String intitule, Set<OffresEmploi> offresEmplois, Set<Candidature> candidatures) {
       this.id = id;
       this.intitule = intitule;
       this.offresEmplois = offresEmplois;
       this.candidatures = candidatures;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule")
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauxQualification")
    public Set<OffresEmploi> getOffresEmplois() {
        return this.offresEmplois;
    }
    
    public void setOffresEmplois(Set<OffresEmploi> offresEmplois) {
        this.offresEmplois = offresEmplois;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauxQualification")
    public Set<Candidature> getCandidatures() {
        return this.candidatures;
    }
    
    public void setCandidatures(Set<Candidature> candidatures) {
        this.candidatures = candidatures;
    }




}


