package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 9:11:42 PM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * SecteurActivite generated by hbm2java
 */
@Entity
@Table(name="secteur_activite"
    ,schema="public"
)
public class SecteurActivite  implements java.io.Serializable {


     private int id;
     private String intitule;
     private Set<IndexSecteurCandidature> indexSecteurCandidatures = new HashSet<IndexSecteurCandidature>(0);
     private Set<IndexSecteurOffre> indexSecteurOffres = new HashSet<IndexSecteurOffre>(0);

    public SecteurActivite() {
    }

	
    public SecteurActivite(int id, String intitule) {
        this.id = id;
        this.intitule = intitule;
    }
    public SecteurActivite(int id, String intitule, Set<IndexSecteurCandidature> indexSecteurCandidatures, Set<IndexSecteurOffre> indexSecteurOffres) {
       this.id = id;
       this.intitule = intitule;
       this.indexSecteurCandidatures = indexSecteurCandidatures;
       this.indexSecteurOffres = indexSecteurOffres;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule", nullable=false, length=50)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="secteurActivite")
    public Set<IndexSecteurCandidature> getIndexSecteurCandidatures() {
        return this.indexSecteurCandidatures;
    }
    
    public void setIndexSecteurCandidatures(Set<IndexSecteurCandidature> indexSecteurCandidatures) {
        this.indexSecteurCandidatures = indexSecteurCandidatures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="secteurActivite")
    public Set<IndexSecteurOffre> getIndexSecteurOffres() {
        return this.indexSecteurOffres;
    }
    
    public void setIndexSecteurOffres(Set<IndexSecteurOffre> indexSecteurOffres) {
        this.indexSecteurOffres = indexSecteurOffres;
    }




}


